# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-09 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogiditem',
            name='catalogId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='catalogiditem',
            name='fatherId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='catalogiditem',
            name='name',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='catalogiditem_1',
            name='catalogId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='catalogiditem_1',
            name='fatherId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='catalogiditem_1',
            name='name',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='catalogiditem_2',
            name='catalogId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='catalogiditem_2',
            name='fatherId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='catalogiditem_2',
            name='icon_url',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='catalogiditem_2',
            name='name',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='activity',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='activityDesc',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='attrLabels',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='boughtFlag',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='brandId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='brandName',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='buyType',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='byName',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='comments',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='fatherid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='gift',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='goldMedalScore',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='goodsUserGrade',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='goodsUserGradeRate',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='goodsid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='groupId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='img',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='isGoldMedal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='isHaiTao',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='itemId',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='marketPrice',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='materialtype',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='morePrice',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='norms',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='productNo',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='promotionTypes',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='saleType',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='salesCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='sellType',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='showPic',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='skuId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='specialStatus',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='store',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='tcDefId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='tcFlag',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='userGrade',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='venderId',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='venderName',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='venderType',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='approvalnum',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='areaItemId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='brandId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='brandName',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='catalogId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='catalogName',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='drugLevel',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='firstCatalogId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='firstCatalogName',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='frightTemplateId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='gift',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='giftLinkTxt',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='h5GitLink',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='hasCombo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='interceptCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='isHaiTao',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='itemId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='limitCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='mainimg1',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='mainimg2',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='mainimg3',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='mainimg4',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='mainimg5',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='mainimg6',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='materialtype',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='prescription',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='productName',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='productNo',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='saleArea',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='saleType',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='secondCatalogId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='secondCatalogName',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='sellPoint',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='sellType',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='seriesAttrs',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='seriesDisplayMode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='seriesId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='seriesIsMain',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='showPic',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='skuId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='specialStatus',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='storeSchemeId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='supplier',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='userGradecount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='venderId',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
