# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-09 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20181109_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsitem',
            name='pcSalePrice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='prescription',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='price',
            field=models.FloatField(),
        ),
    ]
