# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-09 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20181109_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsitem',
            name='pcSalePrice',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='prescription',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='goodsitem',
            name='price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
